name: Update Xoso Data

on:
  schedule:
    # Chạy mỗi ngày lúc 18:30 (giờ Việt Nam ~ UTC+7)
    - cron: "30 11 * * *"  # 11:30 UTC = 18:30 VN
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python update_xoso.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Cập nhật kết quả xổ số tự động $(date)" || echo "No changes to commit"
          git push
